### ISSUE TITLE
Detalles en Formulario de transferencia de paquetes

### ISSUE THREAD

**Issue by mgisbert** [mgisbert/ultim4tedes1gn#74]
Si muevo un paquete de almacen madera humeda a almacen horno el formulario debe pedirme a que **num de horno** estoy moviendo (camara de secado) asi tambien que **num de secado** es.

Si muevo de almacen Madera Seca a Maquinado me debe pedir el campo **Num de Orden** que sera el listado de Ordenes "activas" del Modulo Ordenes

**Comment by Alucarth** [comment]
estos son datos adicionales que se implementaran en la tabla ahora el tema es que un almacen es generico si deseas implementar  mas campos a un almacen especifico tendriamos que revisar la base de datos
